set-option -sa terminal-overrides ",xterm*:Tc"
#allow mouse
set -g mouse on
#set -g mouse-resize-pane on

# Custom Keybindings
## Rebind leader key to CTRL+SPACE
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix
## Switch to next/previous with SHIFT+ALT+L/H keys
bind -n M-H previous-window
bind -n M-L next-window
# Enter copy mode with <leader> v
bind v copy-mode
bind -n M-v copy-mode
# set vi-mode
set-window-option -g mode-keys vi

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-seletion-and-cancel
# Start windows and panes at 1 instead of 0
set -g base-index 1
set -g pane-base-index 1

# open panes in current directory
bind 'ö' split-window -v -c "#{pane_current_path}"
bind 'ä' split-window -h -c "#{pane_current_path}"
bind ';' split-window -v -c "#{pane_current_path}"
bind "'" split-window -h -c "#{pane_current_path}"

# Set new panes to open in current directory
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'dreamsofcode-io/catppuccin-tmux'
set -g @plugin 'tmux-plugins/tmux-yank'
# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'
set -g allow-passthrough on

set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
